<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1.0, viewport-fit=cover"
  >

  <title>RO’Lyfe Chess™</title>

  <meta
    name="description"
    content="RO’Lyfe Chess — strategic chess powered by the RO’Lyfe Gaming ecosystem."
  >

  <link rel="stylesheet" href="../../shared/theme-engine.css">
  <link rel="stylesheet" href="../../shared/game-ui.css">
  <link rel="stylesheet" href="./chess.css">
</head>

<body
  class="rolyfe-game-page chess-page"
  data-rolyfe-game="chess"
  data-game="chess"
>

  <!-- =========================================================
       RO’LYFE CHESS — GAME SHELL
       ========================================================= -->

  <main
    class="rolyfe-game-shell chess-shell"
    data-rolyfe-game-shell
  >

    <!-- =======================================================
         HEADER
         ======================================================= -->

    <header class="rolyfe-game-header chess-header">

      <div class="game-brand">
        <div class="game-brand-icon">♟</div>

        <div>
          <h1>RO’Lyfe Chess™</h1>
          <p>Strategic Intelligence • Chess Board</p>
        </div>
      </div>

      <div class="header-actions">

        <button
          id="themeButton"
          class="game-btn secondary-btn"
          type="button"
          title="Change chess theme"
        >
          🎨 Theme
        </button>

      </div>

    </header>


    <!-- =======================================================
         GAME STATUS BAR
         ======================================================= -->

    <section class="game-status-bar">

      <div class="status-item">
        <span class="status-label">GAME</span>
        <strong id="gameStatus">READY</strong>
      </div>

      <div class="status-item">
        <span class="status-label">TURN</span>
        <strong id="turnStatus">WHITE</strong>
      </div>

      <div class="status-item">
        <span class="status-label">MODE</span>
        <strong id="modeStatus">PLAYER VS PLAYER</strong>
      </div>

      <div class="status-item">
        <span class="status-label">MOVE</span>
        <strong id="moveNumber">1</strong>
      </div>

    </section>


    <!-- =======================================================
         MAIN GAME AREA
         ======================================================= -->

    <section class="chess-main-layout">

      <!-- =====================================================
           LEFT / MAIN BOARD
           ===================================================== -->

      <section class="chess-board-section">

        <!-- WHITE PLAYER -->
        <div
          class="chess-player-card player-card white-player-card"
          data-player="white"
        >

          <div class="player-avatar white-avatar">
            ♔
          </div>

          <div class="player-details">

            <span class="player-side-label">
              WHITE
            </span>

            <strong
              id="whitePlayerName"
              class="player-name"
            >
              Player 1
            </strong>

            <span
              id="whitePlayerLevel"
              class="player-level"
            >
              Player
            </span>

          </div>

          <div
            id="whiteClock"
            class="player-clock"
          >
            10:00
          </div>

        </div>


        <!-- CHESS BOARD -->

        <div
          id="chessBoard"
          class="chess-board"
          role="grid"
          aria-label="RO’Lyfe Chess board"
          tabindex="0"
        >
          <!--
            Chess squares and pieces are generated by chess.js.
          -->
        </div>


        <!-- BLACK PLAYER -->

        <div
          class="chess-player-card player-card black-player-card"
          data-player="black"
        >

          <div class="player-avatar black-avatar">
            ♚
          </div>

          <div class="player-details">

            <span class="player-side-label">
              BLACK
            </span>

            <strong
              id="blackPlayerName"
              class="player-name"
            >
              Player 2
            </strong>

            <span
              id="blackPlayerLevel"
              class="player-level"
            >
              Player
            </span>

          </div>

          <div
            id="blackClock"
            class="player-clock"
          >
            10:00
          </div>

        </div>


        <!-- BOARD STATUS -->

        <div class="board-status-panel">

          <div class="board-status-item">

            <span class="status-label">
              POSITION
            </span>

            <strong id="checkStatus">
              SAFE
            </strong>

          </div>

          <div class="board-status-item">

            <span class="status-label">
              LAST MOVE
            </span>

            <strong id="moveStatus">
              —
            </strong>

          </div>

        </div>

      </section>


      <!-- =====================================================
           CONTROL / INTELLIGENCE PANEL
           ===================================================== -->

      <aside class="chess-control-panel">


        <!-- ===================================================
             GAME SETUP
             =================================================== -->

        <section class="game-panel setup-panel">

          <div class="panel-heading">

            <div>
              <span class="panel-kicker">
                RO’LYFE CHESS
              </span>

              <h2>Game Setup</h2>
            </div>

            <span class="panel-icon">
              ⚙️
            </span>

          </div>


          <!-- GAME MODE -->

          <div class="control-group">

            <label for="gameMode">
              Game Mode
            </label>

            <select
              id="gameMode"
              class="game-select"
            >

              <option value="pvp">
                Player vs Player
              </option>

              <option value="pve">
                Player vs ACE
              </option>

              <option value="eve">
                ACE vs EMG
              </option>

              <option value="battle">
                Player vs EMG
              </option>

            </select>

          </div>


          <!-- AI PROFILE -->

          <div class="control-group">

            <label for="aiProfile">
              AI Profile
            </label>

            <select
              id="aiProfile"
              class="game-select"
            >

              <option value="startup">
                START-UP
              </option>

              <option value="credit">
                CREDIT
              </option>

              <option value="line">
                LINE OF CREDIT
              </option>

              <option value="investor">
                INVESTOR
              </option>

              <option value="sevenfigures">
                7FIGURES
              </option>

              <option value="ace">
                ACE
              </option>

              <option value="emg">
                EMG
              </option>

            </select>

          </div>


          <!-- DIFFICULTY -->

          <div class="control-group">

            <label for="difficultyLevel">
              Difficulty
            </label>

            <select
              id="difficultyLevel"
              class="game-select"
            >

              <option value="1">
                Start-Up
              </option>

              <option value="2">
                Investor
              </option>

              <option value="3">
                7Figures
              </option>

            </select>

          </div>


          <!-- AI SPEED -->

          <div class="control-group">

            <label for="aiSpeed">
              AI Speed
            </label>

            <select
              id="aiSpeed"
              class="game-select"
            >

              <option value="slow">
                Slow
              </option>

              <option
                value="normal"
                selected
              >
                Normal
              </option>

              <option value="fast">
                Fast
              </option>

            </select>

          </div>

        </section>


        <!-- ===================================================
             PLAYERS
             =================================================== -->

        <section class="game-panel players-panel">

          <div class="panel-heading">

            <div>
              <span class="panel-kicker">
                COMMAND CENTER
              </span>

              <h2>Players</h2>
            </div>

            <span class="panel-icon">
              ♟
            </span>

          </div>


          <div class="mini-player-card white-mini-player">

            <div class="mini-player-piece">
              ♔
            </div>

            <div class="mini-player-info">

              <span>WHITE</span>

              <strong
                data-player-name="white"
              >
                Player 1
              </strong>

            </div>

            <div
              class="mini-player-score"
              id="whiteScore"
            >
              0
            </div>

          </div>


          <div class="mini-player-card black-mini-player">

            <div class="mini-player-piece">
              ♚
            </div>

            <div class="mini-player-info">

              <span>BLACK</span>

              <strong
                data-player-name="black"
              >
                Player 2
              </strong>

            </div>

            <div
              class="mini-player-score"
              id="blackScore"
            >
              0
            </div>

          </div>

        </section>


        <!-- ===================================================
             CONTROLS
             =================================================== -->

        <section class="game-panel controls-panel">

          <div class="panel-heading">

            <div>
              <span class="panel-kicker">
                GAME CONTROL
              </span>

              <h2>Controls</h2>
            </div>

            <span class="panel-icon">
              🎮
            </span>

          </div>


          <div class="control-button-grid">

            <button
              id="startGameButton"
              class="game-btn primary-btn"
              type="button"
            >
              ▶ Start Game
            </button>


            <button
              id="aiStartButton"
              class="game-btn ai-btn"
              type="button"
            >
              🤖 AI vs AI
            </button>


            <button
              id="pauseGameButton"
              class="game-btn secondary-btn"
              type="button"
            >
              ⏸ Pause
            </button>


            <button
              id="resignButton"
              class="game-btn danger-btn"
              type="button"
            >
              🏳 Resign
            </button>


            <button
              id="resetGameButton"
              class="game-btn secondary-btn"
              type="button"
            >
              🔄 Reset
            </button>

          </div>

        </section>


        <!-- ===================================================
             MOVE HISTORY
             =================================================== -->

        <section class="game-panel history-panel">

          <div class="panel-heading">

            <div>
              <span class="panel-kicker">
                MATCH RECORD
              </span>

              <h2>Move History</h2>
            </div>

            <span class="panel-icon">
              📜
            </span>

          </div>


          <div
            id="moveHistory"
            class="move-history"
            aria-live="polite"
          >

            <div class="history-empty">
              No moves yet.
            </div>

          </div>


          <button
            id="clearHistoryButton"
            class="game-btn small-btn secondary-btn"
            type="button"
          >
            Clear History
          </button>

        </section>


        <!-- ===================================================
             CAPTURED PIECES
             =================================================== -->

        <section class="game-panel captured-panel">

          <div class="panel-heading">

            <div>
              <span class="panel-kicker">
                BOARD INTELLIGENCE
              </span>

              <h2>Captured Pieces</h2>
            </div>

            <span class="panel-icon">
              ⚔️
            </span>

          </div>


          <div class="captured-row">

            <div class="captured-side">

              <span class="captured-label">
                WHITE
              </span>

              <div
                id="whiteCaptured"
                class="captured-pieces"
              >
                —
              </div>

            </div>


            <div class="captured-side">

              <span class="captured-label">
                BLACK
              </span>

              <div
                id="blackCaptured"
                class="captured-pieces"
              >
                —
              </div>

            </div>

          </div>

        </section>


        <!-- ===================================================
             PLAYER STATS
             =================================================== -->

        <section class="game-panel stats-panel">

          <div class="panel-heading">

            <div>
              <span class="panel-kicker">
                RO’LYFE PROFILE
              </span>

              <h2>Commander Stats</h2>
            </div>

            <span class="panel-icon">
              📊
            </span>

          </div>


          <div class="stats-grid">

            <div class="stat-box">

              <span>
                Rating
              </span>

              <strong id="commanderRating">
                1200
              </strong>

            </div>


            <div class="stat-box">

              <span>
                Games
              </span>

              <strong id="gamesPlayed">
                0
              </strong>

            </div>


            <div class="stat-box">

              <span>
                Wins
              </span>

              <strong id="gamesWon">
                0
              </strong>

            </div>


            <div class="stat-box">

              <span>
                Win Rate
              </span>

              <strong id="winRate">
                0%
              </strong>

            </div>

          </div>

        </section>

      </aside>

    </section>


    <!-- =======================================================
         GAME FOOTER
         ======================================================= -->

    <footer class="chess-footer">

      <div>
        <strong>RO’Lyfe Chess™</strong>
        <span>Strategic Intelligence Gaming</span>
      </div>

      <div class="footer-status">
        <span class="status-dot"></span>
        RO’Lyfe Gaming System
      </div>

    </footer>

  </main>


  <!-- =========================================================
       GAME OVERLAY
       ========================================================= -->

  <div
    id="gameOverlay"
    class="rolyfe-game-overlay chess-overlay"
    data-game-overlay
    aria-hidden="true"
  >

    <div class="overlay-card">

      <div
        id="overlayIcon"
        class="overlay-icon"
      >
        ♟
      </div>

      <h2 id="overlayTitle">
        Game Over
      </h2>

      <p id="overlayMessage">
        The match has ended.
      </p>


      <div class="overlay-actions">

        <button
          id="overlayRestartButton"
          class="game-btn primary-btn"
          type="button"
        >
          🔄 Play Again
        </button>

        <button
          id="overlayCloseButton"
          class="game-btn secondary-btn"
          type="button"
        >
          Close
        </button>

      </div>

    </div>

  </div>


  <!-- =========================================================
       SHARED RO’LYFE GAMING SYSTEMS
       ========================================================= -->

  <script src="../../shared/physics-engine.js"></script>
  <script src="../../shared/audio.js"></script>
  <script src="../../shared/timer.js"></script>
  <script src="../../shared/player-system.js"></script>
  <script src="../../shared/theme-engine.js"></script>
  <script src="../../shared/game-ui.js"></script>
  <script src="../../shared/ai-engine.js"></script>


  <!-- =========================================================
       CHESS SYSTEMS
       ========================================================= -->

  <script src="./themes.js"></script>
  <script src="./chess.js"></script>

</body>
</html>
